"""erste migration

Revision ID: 07f56b71e1bd
Revises: 
Create Date: 2026-03-14 16:47:02.675069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f56b71e1bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projekt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prognose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wert', sa.Float(), nullable=True),
    sa.Column('projekt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projekt_id'], ['projekt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prognose')
    op.drop_table('projekt')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
